from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Protocol

from tasy_insercao.domain.integracao.models import (
    EventoFilaCartao,
    ResultadoIntegracao,
    TransacaoCartao,
)


class StagingRepositoryPort(Protocol):
    def get_by_id_stone(self, id_stone: str) -> tuple | None: ...
    def ensure_registro(self, tx: TransacaoCartao, status: int, obs: str, cd_caixa: int | None = None) -> int | None: ...
    def update_status(self, nr_sequencia: int | None, status: int, obs: str) -> None: ...
    def get_maquininha_config(self, nr_serie: str) -> dict: ...
    def get_bandeira_tasy(self, tipo_api: str, bandeira: str) -> int | None: ...


class TasyRepositoryPort(Protocol):
    def exists_movto_by_id_stone(self, id_stone: str) -> bool: ...
    def ensure_caixa_saldo_diario(self, nr_seq_caixa: int, dt_saldo: str) -> int: ...
    def inserir_caixa_receb(self, nr_seq_saldo: int, dt: str, cd_trans_fin: int) -> int: ...
    def inserir_movto_cartao(self, params: dict) -> None: ...
    def inserir_movto_cartao_parcelado(self, params: dict) -> None: ...
    def inserir_documento(self, params: dict) -> None: ...


class IntegrarTransacaoCartaoPort(ABC):
    @abstractmethod
    def execute(self, tx: TransacaoCartao) -> ResultadoIntegracao: ...


class RetryPublisherPort(Protocol):
    async def publish_retry(self, evento: EventoFilaCartao, delay_seconds: int) -> None: ...
    async def publish_dlq(self, evento: EventoFilaCartao) -> None: ...
